// Code generated by protoc-gen-go. DO NOT EDIT.
// source: generic_driver.proto

/*
Package generic_driver is a generated protocol buffer package.

It is generated from these files:
	generic_driver.proto

It has these top-level messages:
	Empty
	DriverFlags
	Flag
	DriverOptions
	StringSlice
	ClusterGetRequest
	ClusterInfo
*/
package generic_driver

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Empty struct {
}

func (m *Empty) Reset()                    { *m = Empty{} }
func (m *Empty) String() string            { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()               {}
func (*Empty) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type DriverFlags struct {
	Options map[string]*Flag `protobuf:"bytes,1,rep,name=options" json:"options,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
}

func (m *DriverFlags) Reset()                    { *m = DriverFlags{} }
func (m *DriverFlags) String() string            { return proto.CompactTextString(m) }
func (*DriverFlags) ProtoMessage()               {}
func (*DriverFlags) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *DriverFlags) GetOptions() map[string]*Flag {
	if m != nil {
		return m.Options
	}
	return nil
}

type Flag struct {
	Type  string `protobuf:"bytes,1,opt,name=type" json:"type,omitempty"`
	Usage string `protobuf:"bytes,2,opt,name=usage" json:"usage,omitempty"`
}

func (m *Flag) Reset()                    { *m = Flag{} }
func (m *Flag) String() string            { return proto.CompactTextString(m) }
func (*Flag) ProtoMessage()               {}
func (*Flag) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Flag) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Flag) GetUsage() string {
	if m != nil {
		return m.Usage
	}
	return ""
}

type DriverOptions struct {
	BoolOptions        map[string]bool         `protobuf:"bytes,1,rep,name=bool_options,json=boolOptions" json:"bool_options,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	StringOptions      map[string]string       `protobuf:"bytes,2,rep,name=string_options,json=stringOptions" json:"string_options,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	IntOptions         map[string]int64        `protobuf:"bytes,3,rep,name=int_options,json=intOptions" json:"int_options,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	StringSliceOptions map[string]*StringSlice `protobuf:"bytes,4,rep,name=string_slice_options,json=stringSliceOptions" json:"string_slice_options,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
}

func (m *DriverOptions) Reset()                    { *m = DriverOptions{} }
func (m *DriverOptions) String() string            { return proto.CompactTextString(m) }
func (*DriverOptions) ProtoMessage()               {}
func (*DriverOptions) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *DriverOptions) GetBoolOptions() map[string]bool {
	if m != nil {
		return m.BoolOptions
	}
	return nil
}

func (m *DriverOptions) GetStringOptions() map[string]string {
	if m != nil {
		return m.StringOptions
	}
	return nil
}

func (m *DriverOptions) GetIntOptions() map[string]int64 {
	if m != nil {
		return m.IntOptions
	}
	return nil
}

func (m *DriverOptions) GetStringSliceOptions() map[string]*StringSlice {
	if m != nil {
		return m.StringSliceOptions
	}
	return nil
}

type StringSlice struct {
	Value []string `protobuf:"bytes,1,rep,name=value" json:"value,omitempty"`
}

func (m *StringSlice) Reset()                    { *m = StringSlice{} }
func (m *StringSlice) String() string            { return proto.CompactTextString(m) }
func (*StringSlice) ProtoMessage()               {}
func (*StringSlice) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *StringSlice) GetValue() []string {
	if m != nil {
		return m.Value
	}
	return nil
}

type ClusterGetRequest struct {
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
}

func (m *ClusterGetRequest) Reset()                    { *m = ClusterGetRequest{} }
func (m *ClusterGetRequest) String() string            { return proto.CompactTextString(m) }
func (*ClusterGetRequest) ProtoMessage()               {}
func (*ClusterGetRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *ClusterGetRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type ClusterInfo struct {
	Version             string            `protobuf:"bytes,1,opt,name=version" json:"version,omitempty"`
	ServiceAccountToken string            `protobuf:"bytes,2,opt,name=service_account_token,json=serviceAccountToken" json:"service_account_token,omitempty"`
	Endpoint            string            `protobuf:"bytes,3,opt,name=endpoint" json:"endpoint,omitempty"`
	Username            string            `protobuf:"bytes,4,opt,name=username" json:"username,omitempty"`
	Password            string            `protobuf:"bytes,5,opt,name=password" json:"password,omitempty"`
	RootCaCertificate   string            `protobuf:"bytes,6,opt,name=root_ca_certificate,json=rootCaCertificate" json:"root_ca_certificate,omitempty"`
	ClientCertificate   string            `protobuf:"bytes,7,opt,name=client_certificate,json=clientCertificate" json:"client_certificate,omitempty"`
	ClientKey           string            `protobuf:"bytes,8,opt,name=client_key,json=clientKey" json:"client_key,omitempty"`
	NodeCount           int64             `protobuf:"varint,9,opt,name=node_count,json=nodeCount" json:"node_count,omitempty"`
	Metadata            map[string]string `protobuf:"bytes,10,rep,name=metadata" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
}

func (m *ClusterInfo) Reset()                    { *m = ClusterInfo{} }
func (m *ClusterInfo) String() string            { return proto.CompactTextString(m) }
func (*ClusterInfo) ProtoMessage()               {}
func (*ClusterInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *ClusterInfo) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *ClusterInfo) GetServiceAccountToken() string {
	if m != nil {
		return m.ServiceAccountToken
	}
	return ""
}

func (m *ClusterInfo) GetEndpoint() string {
	if m != nil {
		return m.Endpoint
	}
	return ""
}

func (m *ClusterInfo) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *ClusterInfo) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *ClusterInfo) GetRootCaCertificate() string {
	if m != nil {
		return m.RootCaCertificate
	}
	return ""
}

func (m *ClusterInfo) GetClientCertificate() string {
	if m != nil {
		return m.ClientCertificate
	}
	return ""
}

func (m *ClusterInfo) GetClientKey() string {
	if m != nil {
		return m.ClientKey
	}
	return ""
}

func (m *ClusterInfo) GetNodeCount() int64 {
	if m != nil {
		return m.NodeCount
	}
	return 0
}

func (m *ClusterInfo) GetMetadata() map[string]string {
	if m != nil {
		return m.Metadata
	}
	return nil
}

func init() {
	proto.RegisterType((*Empty)(nil), "generic_driver.Empty")
	proto.RegisterType((*DriverFlags)(nil), "generic_driver.DriverFlags")
	proto.RegisterType((*Flag)(nil), "generic_driver.Flag")
	proto.RegisterType((*DriverOptions)(nil), "generic_driver.DriverOptions")
	proto.RegisterType((*StringSlice)(nil), "generic_driver.StringSlice")
	proto.RegisterType((*ClusterGetRequest)(nil), "generic_driver.ClusterGetRequest")
	proto.RegisterType((*ClusterInfo)(nil), "generic_driver.ClusterInfo")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Driver service

type DriverClient interface {
	Create(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error)
	Update(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error)
	Get(ctx context.Context, in *ClusterGetRequest, opts ...grpc.CallOption) (*ClusterInfo, error)
	Remove(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error)
	GetDriverCreateOptions(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*DriverFlags, error)
	GetDriverUpdateOptions(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*DriverFlags, error)
	SetDriverOptions(ctx context.Context, in *DriverOptions, opts ...grpc.CallOption) (*Empty, error)
}

type driverClient struct {
	cc *grpc.ClientConn
}

func NewDriverClient(cc *grpc.ClientConn) DriverClient {
	return &driverClient{cc}
}

func (c *driverClient) Create(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := grpc.Invoke(ctx, "/generic_driver.Driver/Create", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *driverClient) Update(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := grpc.Invoke(ctx, "/generic_driver.Driver/Update", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *driverClient) Get(ctx context.Context, in *ClusterGetRequest, opts ...grpc.CallOption) (*ClusterInfo, error) {
	out := new(ClusterInfo)
	err := grpc.Invoke(ctx, "/generic_driver.Driver/Get", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *driverClient) Remove(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := grpc.Invoke(ctx, "/generic_driver.Driver/Remove", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *driverClient) GetDriverCreateOptions(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*DriverFlags, error) {
	out := new(DriverFlags)
	err := grpc.Invoke(ctx, "/generic_driver.Driver/GetDriverCreateOptions", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *driverClient) GetDriverUpdateOptions(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*DriverFlags, error) {
	out := new(DriverFlags)
	err := grpc.Invoke(ctx, "/generic_driver.Driver/GetDriverUpdateOptions", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *driverClient) SetDriverOptions(ctx context.Context, in *DriverOptions, opts ...grpc.CallOption) (*Empty, error) {
	out := new(Empty)
	err := grpc.Invoke(ctx, "/generic_driver.Driver/SetDriverOptions", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Driver service

type DriverServer interface {
	Create(context.Context, *Empty) (*Empty, error)
	Update(context.Context, *Empty) (*Empty, error)
	Get(context.Context, *ClusterGetRequest) (*ClusterInfo, error)
	Remove(context.Context, *Empty) (*Empty, error)
	GetDriverCreateOptions(context.Context, *Empty) (*DriverFlags, error)
	GetDriverUpdateOptions(context.Context, *Empty) (*DriverFlags, error)
	SetDriverOptions(context.Context, *DriverOptions) (*Empty, error)
}

func RegisterDriverServer(s *grpc.Server, srv DriverServer) {
	s.RegisterService(&_Driver_serviceDesc, srv)
}

func _Driver_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DriverServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/generic_driver.Driver/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DriverServer).Create(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Driver_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DriverServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/generic_driver.Driver/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DriverServer).Update(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Driver_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClusterGetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DriverServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/generic_driver.Driver/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DriverServer).Get(ctx, req.(*ClusterGetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Driver_Remove_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DriverServer).Remove(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/generic_driver.Driver/Remove",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DriverServer).Remove(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Driver_GetDriverCreateOptions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DriverServer).GetDriverCreateOptions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/generic_driver.Driver/GetDriverCreateOptions",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DriverServer).GetDriverCreateOptions(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Driver_GetDriverUpdateOptions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DriverServer).GetDriverUpdateOptions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/generic_driver.Driver/GetDriverUpdateOptions",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DriverServer).GetDriverUpdateOptions(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Driver_SetDriverOptions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DriverOptions)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DriverServer).SetDriverOptions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/generic_driver.Driver/SetDriverOptions",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DriverServer).SetDriverOptions(ctx, req.(*DriverOptions))
	}
	return interceptor(ctx, in, info, handler)
}

var _Driver_serviceDesc = grpc.ServiceDesc{
	ServiceName: "generic_driver.Driver",
	HandlerType: (*DriverServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _Driver_Create_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _Driver_Update_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _Driver_Get_Handler,
		},
		{
			MethodName: "Remove",
			Handler:    _Driver_Remove_Handler,
		},
		{
			MethodName: "GetDriverCreateOptions",
			Handler:    _Driver_GetDriverCreateOptions_Handler,
		},
		{
			MethodName: "GetDriverUpdateOptions",
			Handler:    _Driver_GetDriverUpdateOptions_Handler,
		},
		{
			MethodName: "SetDriverOptions",
			Handler:    _Driver_SetDriverOptions_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "generic_driver.proto",
}

func init() { proto.RegisterFile("generic_driver.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 696 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x95, 0xdf, 0x6e, 0xd3, 0x4a,
	0x10, 0xc6, 0x4f, 0xea, 0xfc, 0x1d, 0xb7, 0x3d, 0xed, 0x36, 0x3d, 0xc7, 0x72, 0x55, 0xa9, 0xc7,
	0xe7, 0x82, 0x80, 0x54, 0xab, 0x04, 0x21, 0x55, 0x20, 0x10, 0x34, 0x94, 0xa8, 0x20, 0x0a, 0xa4,
	0x20, 0x2e, 0x23, 0xc7, 0xd9, 0x46, 0x56, 0x9d, 0x5d, 0xb3, 0xbb, 0x09, 0xca, 0xa3, 0x70, 0xcd,
	0x0b, 0xf1, 0x1e, 0xbc, 0x04, 0xda, 0x5d, 0xdb, 0xb1, 0xdd, 0x24, 0xa5, 0x70, 0xe7, 0x9d, 0xef,
	0x9b, 0x5f, 0x66, 0x66, 0xc7, 0x0e, 0x34, 0x47, 0x98, 0x60, 0x16, 0xf8, 0xfd, 0x21, 0x0b, 0xa6,
	0x98, 0xb9, 0x11, 0xa3, 0x82, 0xa2, 0xcd, 0x7c, 0xd4, 0xa9, 0x41, 0xe5, 0x74, 0x1c, 0x89, 0x99,
	0xf3, 0xad, 0x04, 0xe6, 0x0b, 0x15, 0x7b, 0x19, 0x7a, 0x23, 0x8e, 0x4e, 0xa0, 0x46, 0x23, 0x11,
	0x50, 0xc2, 0xad, 0xd2, 0x81, 0xd1, 0x32, 0xdb, 0x2d, 0xb7, 0x00, 0xcc, 0xb8, 0xdd, 0xb7, 0xda,
	0x7a, 0x4a, 0x04, 0x9b, 0xf5, 0x92, 0x44, 0xfb, 0x1d, 0xac, 0x67, 0x05, 0xb4, 0x05, 0xc6, 0x15,
	0x9e, 0x59, 0xa5, 0x83, 0x52, 0xab, 0xd1, 0x93, 0x8f, 0xe8, 0x1e, 0x54, 0xa6, 0x5e, 0x38, 0xc1,
	0xd6, 0xda, 0x41, 0xa9, 0x65, 0xb6, 0x9b, 0xc5, 0xdf, 0x90, 0xf4, 0x9e, 0xb6, 0x3c, 0x5a, 0x3b,
	0x2e, 0x39, 0x47, 0x50, 0x96, 0x21, 0x84, 0xa0, 0x2c, 0x66, 0x11, 0x8e, 0x51, 0xea, 0x19, 0x35,
	0xa1, 0x32, 0xe1, 0xde, 0x48, 0xb3, 0x1a, 0x3d, 0x7d, 0x70, 0xbe, 0x56, 0x60, 0x43, 0x57, 0x1a,
	0x97, 0x82, 0xde, 0xc3, 0xfa, 0x80, 0xd2, 0xb0, 0x9f, 0x6f, 0xcf, 0x5d, 0xdc, 0x5e, 0x9c, 0xe4,
	0x9e, 0x50, 0x1a, 0xe6, 0x9a, 0x34, 0x07, 0xf3, 0x08, 0xfa, 0x04, 0x9b, 0x5c, 0xb0, 0x80, 0x8c,
	0x52, 0xe8, 0x9a, 0x82, 0x1e, 0xad, 0x86, 0x5e, 0xa8, 0x9c, 0x1c, 0x76, 0x83, 0x67, 0x63, 0xe8,
	0x1c, 0xcc, 0x80, 0x88, 0x94, 0x6a, 0x28, 0xea, 0xe1, 0x6a, 0xea, 0x19, 0x11, 0x39, 0x24, 0x04,
	0x69, 0x00, 0x8d, 0xa0, 0x19, 0x17, 0xca, 0xc3, 0xc0, 0xc7, 0x29, 0xb8, 0xac, 0xc0, 0x0f, 0x7f,
	0xa5, 0xdc, 0x0b, 0x99, 0x98, 0xfb, 0x01, 0xc4, 0xaf, 0x09, 0xf6, 0x53, 0xd8, 0x2a, 0x8e, 0x6c,
	0xc1, 0xf5, 0x37, 0xb3, 0xd7, 0x5f, 0xcf, 0x5c, 0xb4, 0xfd, 0x0c, 0xd0, 0xf5, 0xe9, 0xdc, 0x44,
	0x68, 0x64, 0x09, 0x4f, 0xe0, 0xef, 0xc2, 0x24, 0x6e, 0x4a, 0x37, 0xb2, 0xe9, 0x03, 0xf8, 0x77,
	0x49, 0xbf, 0x0b, 0x30, 0xf7, 0xf3, 0x6b, 0xbc, 0x57, 0x9c, 0x63, 0x86, 0x94, 0xdd, 0xe6, 0xff,
	0xc1, 0xcc, 0x28, 0xf3, 0x62, 0xe4, 0x46, 0x26, 0xbd, 0x38, 0x77, 0x60, 0xbb, 0x13, 0x4e, 0xb8,
	0xc0, 0xac, 0x8b, 0x45, 0x0f, 0x7f, 0x9e, 0x60, 0x2e, 0xe4, 0xfe, 0x13, 0x6f, 0x9c, 0xee, 0xbf,
	0x7c, 0x76, 0xbe, 0x1b, 0x60, 0xc6, 0xce, 0x33, 0x72, 0x49, 0x91, 0x05, 0xb5, 0x29, 0x66, 0x3c,
	0xa0, 0x24, 0xb6, 0x25, 0x47, 0xd4, 0x86, 0x5d, 0x8e, 0xd9, 0x54, 0x2e, 0x80, 0xe7, 0xfb, 0x74,
	0x42, 0x44, 0x5f, 0xd0, 0x2b, 0x4c, 0xe2, 0x21, 0xee, 0xc4, 0xe2, 0x73, 0xad, 0x7d, 0x90, 0x12,
	0xb2, 0xa1, 0x8e, 0xc9, 0x30, 0xa2, 0x01, 0x11, 0x96, 0xa1, 0x6c, 0xe9, 0x59, 0x6a, 0x13, 0x8e,
	0x99, 0xaa, 0xa8, 0xac, 0xb5, 0xe4, 0x2c, 0xb5, 0xc8, 0xe3, 0xfc, 0x0b, 0x65, 0x43, 0xab, 0xa2,
	0xb5, 0xe4, 0x8c, 0x5c, 0xd8, 0x61, 0x94, 0x8a, 0xbe, 0xef, 0xf5, 0x7d, 0xcc, 0x44, 0x70, 0x19,
	0xf8, 0x9e, 0xc0, 0x56, 0x55, 0xd9, 0xb6, 0xa5, 0xd4, 0xf1, 0x3a, 0x73, 0x01, 0x1d, 0x02, 0xf2,
	0xc3, 0x00, 0x13, 0x91, 0xb3, 0xd7, 0xb4, 0x5d, 0x2b, 0x59, 0xfb, 0x3e, 0x40, 0x6c, 0x97, 0xd7,
	0x55, 0x57, 0xb6, 0x86, 0x8e, 0xbc, 0xc6, 0x33, 0x29, 0x13, 0x3a, 0xc4, 0x7d, 0xd5, 0xa4, 0xd5,
	0x50, 0x0b, 0xd0, 0x90, 0x91, 0x8e, 0x0c, 0xa0, 0x53, 0xa8, 0x8f, 0xb1, 0xf0, 0x86, 0x9e, 0xf0,
	0x2c, 0x50, 0xaf, 0xc7, 0xdd, 0xe2, 0xb5, 0x66, 0xa6, 0xed, 0xbe, 0x89, 0xbd, 0xfa, 0x95, 0x48,
	0x53, 0xed, 0xc7, 0xb0, 0x91, 0x93, 0x6e, 0xb3, 0xc3, 0xed, 0x1f, 0x06, 0x54, 0xf5, 0x3b, 0x88,
	0x8e, 0xa1, 0xda, 0x61, 0x58, 0xb6, 0xb5, 0x5b, 0x2c, 0x43, 0x7d, 0xc0, 0xed, 0xc5, 0x61, 0xe7,
	0x2f, 0x99, 0xf9, 0x31, 0x1a, 0xfe, 0x4e, 0x66, 0x17, 0x8c, 0x2e, 0x16, 0xe8, 0xbf, 0x25, 0x7d,
	0xcf, 0xf7, 0xd1, 0xde, 0x5b, 0x31, 0x1a, 0x5d, 0x42, 0x0f, 0x8f, 0xe9, 0xf4, 0xf6, 0x25, 0x9c,
	0xc3, 0x3f, 0x5d, 0x2c, 0xf4, 0x0c, 0x74, 0xff, 0xc9, 0xa7, 0x6c, 0x09, 0x69, 0x6f, 0xc5, 0xdf,
	0x54, 0x81, 0xa7, 0xa7, 0xf2, 0x67, 0xbc, 0x57, 0xb0, 0x75, 0x91, 0xf0, 0x12, 0xd2, 0xfe, 0xca,
	0xcf, 0xe8, 0xd2, 0x5e, 0x07, 0x55, 0xf5, 0x17, 0xfd, 0xe0, 0x67, 0x00, 0x00, 0x00, 0xff, 0xff,
	0xb7, 0x88, 0x55, 0x09, 0xba, 0x07, 0x00, 0x00,
}
